// Landen — voor landcode/prefix telefoon (wereldwijd)
export const COUNTRIES: Record<string, { flag: string; prefix: string; name: string }> = {
  NL: { flag: '🇳🇱', prefix: '+31',  name: 'Nederland' },
  BE: { flag: '🇧🇪', prefix: '+32',  name: 'België' },
  DE: { flag: '🇩🇪', prefix: '+49',  name: 'Deutschland' },
  FR: { flag: '🇫🇷', prefix: '+33',  name: 'France' },
  GB: { flag: '🇬🇧', prefix: '+44',  name: 'United Kingdom' },
  US: { flag: '🇺🇸', prefix: '+1',   name: 'United States' },
  CA: { flag: '🇨🇦', prefix: '+1',   name: 'Canada' },
  AU: { flag: '🇦🇺', prefix: '+61',  name: 'Australia' },
  AT: { flag: '🇦🇹', prefix: '+43',  name: 'Österreich' },
  CH: { flag: '🇨🇭', prefix: '+41',  name: 'Schweiz' },
  ES: { flag: '🇪🇸', prefix: '+34',  name: 'España' },
  IT: { flag: '🇮🇹', prefix: '+39',  name: 'Italia' },
  PT: { flag: '🇵🇹', prefix: '+351', name: 'Portugal' },
  PL: { flag: '🇵🇱', prefix: '+48',  name: 'Polska' },
  TR: { flag: '🇹🇷', prefix: '+90',  name: 'Türkiye' },
  SE: { flag: '🇸🇪', prefix: '+46',  name: 'Sverige' },
  NO: { flag: '🇳🇴', prefix: '+47',  name: 'Norge' },
  DK: { flag: '🇩🇰', prefix: '+45',  name: 'Danmark' },
  FI: { flag: '🇫🇮', prefix: '+358', name: 'Suomi' },
  GR: { flag: '🇬🇷', prefix: '+30',  name: 'Ελλάδα' },
  CZ: { flag: '🇨🇿', prefix: '+420', name: 'Česká republika' },
  SK: { flag: '🇸🇰', prefix: '+421', name: 'Slovensko' },
  HU: { flag: '🇭🇺', prefix: '+36',  name: 'Magyarország' },
  RO: { flag: '🇷🇴', prefix: '+40',  name: 'România' },
  BG: { flag: '🇧🇬', prefix: '+359', name: 'България' },
  HR: { flag: '🇭🇷', prefix: '+385', name: 'Hrvatska' },
  RS: { flag: '🇷🇸', prefix: '+381', name: 'Srbija' },
  SI: { flag: '🇸🇮', prefix: '+386', name: 'Slovenija' },
  IE: { flag: '🇮🇪', prefix: '+353', name: 'Ireland' },
  LU: { flag: '🇱🇺', prefix: '+352', name: 'Luxembourg' },
  LT: { flag: '🇱🇹', prefix: '+370', name: 'Lietuva' },
  LV: { flag: '🇱🇻', prefix: '+371', name: 'Latvija' },
  EE: { flag: '🇪🇪', prefix: '+372', name: 'Eesti' },
  UA: { flag: '🇺🇦', prefix: '+380', name: 'Україна' },
  RU: { flag: '🇷🇺', prefix: '+7',   name: 'Россия' },
  BY: { flag: '🇧🇾', prefix: '+375', name: 'Беларусь' },
  MD: { flag: '🇲🇩', prefix: '+373', name: 'Moldova' },
  AL: { flag: '🇦🇱', prefix: '+355', name: 'Shqipëria' },
  MK: { flag: '🇲🇰', prefix: '+389', name: 'Македонија' },
  BA: { flag: '🇧🇦', prefix: '+387', name: 'Bosna i Hercegovina' },
  ME: { flag: '🇲🇪', prefix: '+382', name: 'Crna Gora' },
  XK: { flag: '🇽🇰', prefix: '+383', name: 'Kosovë' },
  IS: { flag: '🇮🇸', prefix: '+354', name: 'Ísland' },
  MT: { flag: '🇲🇹', prefix: '+356', name: 'Malta' },
  CY: { flag: '🇨🇾', prefix: '+357', name: 'Κύπρος' },
  NZ: { flag: '🇳🇿', prefix: '+64',  name: 'New Zealand' },
  ZA: { flag: '🇿🇦', prefix: '+27',  name: 'South Africa' },
  NG: { flag: '🇳🇬', prefix: '+234', name: 'Nigeria' },
  KE: { flag: '🇰🇪', prefix: '+254', name: 'Kenya' },
  GH: { flag: '🇬🇭', prefix: '+233', name: 'Ghana' },
  EG: { flag: '🇪🇬', prefix: '+20',  name: 'مصر' },
  MA: { flag: '🇲🇦', prefix: '+212', name: 'المغرب' },
  TN: { flag: '🇹🇳', prefix: '+216', name: 'تونس' },
  DZ: { flag: '🇩🇿', prefix: '+213', name: 'الجزائر' },
  ET: { flag: '🇪🇹', prefix: '+251', name: 'Ethiopia' },
  TZ: { flag: '🇹🇿', prefix: '+255', name: 'Tanzania' },
  UG: { flag: '🇺🇬', prefix: '+256', name: 'Uganda' },
  IN: { flag: '🇮🇳', prefix: '+91',  name: 'India' },
  PK: { flag: '🇵🇰', prefix: '+92',  name: 'Pakistan' },
  BD: { flag: '🇧🇩', prefix: '+880', name: 'Bangladesh' },
  LK: { flag: '🇱🇰', prefix: '+94',  name: 'Sri Lanka' },
  NP: { flag: '🇳🇵', prefix: '+977', name: 'Nepal' },
  MM: { flag: '🇲🇲', prefix: '+95',  name: 'Myanmar' },
  TH: { flag: '🇹🇭', prefix: '+66',  name: 'ประเทศไทย' },
  VN: { flag: '🇻🇳', prefix: '+84',  name: 'Việt Nam' },
  ID: { flag: '🇮🇩', prefix: '+62',  name: 'Indonesia' },
  MY: { flag: '🇲🇾', prefix: '+60',  name: 'Malaysia' },
  SG: { flag: '🇸🇬', prefix: '+65',  name: 'Singapore' },
  PH: { flag: '🇵🇭', prefix: '+63',  name: 'Philippines' },
  CN: { flag: '🇨🇳', prefix: '+86',  name: '中国' },
  JP: { flag: '🇯🇵', prefix: '+81',  name: '日本' },
  KR: { flag: '🇰🇷', prefix: '+82',  name: '대한민국' },
  TW: { flag: '🇹🇼', prefix: '+886', name: 'Taiwan' },
  HK: { flag: '🇭🇰', prefix: '+852', name: 'Hong Kong' },
  MO: { flag: '🇲🇴', prefix: '+853', name: 'Macau' },
  KH: { flag: '🇰🇭', prefix: '+855', name: 'Cambodia' },
  LA: { flag: '🇱🇦', prefix: '+856', name: 'Laos' },
  MN: { flag: '🇲🇳', prefix: '+976', name: 'Mongolia' },
  KZ: { flag: '🇰🇿', prefix: '+7',   name: 'Казахстан' },
  UZ: { flag: '🇺🇿', prefix: '+998', name: 'Uzbekistan' },
  AZ: { flag: '🇦🇿', prefix: '+994', name: 'Azərbaycan' },
  GE: { flag: '🇬🇪', prefix: '+995', name: 'საქართველო' },
  AM: { flag: '🇦🇲', prefix: '+374', name: 'Հայաuտան' },
  IL: { flag: '🇮🇱', prefix: '+972', name: 'ישראל' },
  SA: { flag: '🇸🇦', prefix: '+966', name: 'السعودية' },
  AE: { flag: '🇦🇪', prefix: '+971', name: 'الإمارات' },
  QA: { flag: '🇶🇦', prefix: '+974', name: 'قطر' },
  KW: { flag: '🇰🇼', prefix: '+965', name: 'الكويت' },
  BH: { flag: '🇧🇭', prefix: '+973', name: 'البحرين' },
  OM: { flag: '🇴🇲', prefix: '+968', name: 'عُمان' },
  JO: { flag: '🇯🇴', prefix: '+962', name: 'الأردن' },
  LB: { flag: '🇱🇧', prefix: '+961', name: 'لبنان' },
  IQ: { flag: '🇮🇶', prefix: '+964', name: 'العراق' },
  IR: { flag: '🇮🇷', prefix: '+98',  name: 'ایران' },
  AF: { flag: '🇦🇫', prefix: '+93',  name: 'Afghanistan' },
  MX: { flag: '🇲🇽', prefix: '+52',  name: 'México' },
  BR: { flag: '🇧🇷', prefix: '+55',  name: 'Brasil' },
  AR: { flag: '🇦🇷', prefix: '+54',  name: 'Argentina' },
  CL: { flag: '🇨🇱', prefix: '+56',  name: 'Chile' },
  CO: { flag: '🇨🇴', prefix: '+57',  name: 'Colombia' },
  PE: { flag: '🇵🇪', prefix: '+51',  name: 'Perú' },
  VE: { flag: '🇻🇪', prefix: '+58',  name: 'Venezuela' },
  EC: { flag: '🇪🇨', prefix: '+593', name: 'Ecuador' },
  BO: { flag: '🇧🇴', prefix: '+591', name: 'Bolivia' },
  PY: { flag: '🇵🇾', prefix: '+595', name: 'Paraguay' },
  UY: { flag: '🇺🇾', prefix: '+598', name: 'Uruguay' },
  CR: { flag: '🇨🇷', prefix: '+506', name: 'Costa Rica' },
  PA: { flag: '🇵🇦', prefix: '+507', name: 'Panamá' },
  CU: { flag: '🇨🇺', prefix: '+53',  name: 'Cuba' },
  DO: { flag: '🇩🇴', prefix: '+1',   name: 'República Dominicana' },
  JM: { flag: '🇯🇲', prefix: '+1',   name: 'Jamaica' },
};

// Talen — voor de interface
export const LANGUAGES: Record<string, { flag: string; name: string; lang: string; days: string[] }> = {
  nl: { flag: '🇳🇱', name: 'Nederlands',     lang: 'nl', days: ['Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag'] },
  uk: { flag: '🇬🇧', name: 'English (UK)',    lang: 'uk', days: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] },
  us: { flag: '🇺🇸', name: 'English (US)',    lang: 'us', days: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] },
  de: { flag: '🇩🇪', name: 'Deutsch',         lang: 'de', days: ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'] },
  fr: { flag: '🇫🇷', name: 'Français',        lang: 'fr', days: ['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'] },
  es: { flag: '🇪🇸', name: 'Español',         lang: 'es', days: ['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'] },
  it: { flag: '🇮🇹', name: 'Italiano',        lang: 'it', days: ['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'] },
  pl: { flag: '🇵🇱', name: 'Polski',          lang: 'pl', days: ['Poniedziałek','Wtorek','Środa','Czwartek','Piątek','Sobota','Niedziela'] },
  tr: { flag: '🇹🇷', name: 'Türkçe',          lang: 'tr', days: ['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'] },
};
